-- Create a safe query execution function for natural language to SQL conversion
-- This function allows controlled execution of SELECT queries generated by the OSS LLM service

-- Drop the function if it exists
DROP FUNCTION IF EXISTS execute_safe_query(text);

-- Create the function with proper security
CREATE OR REPLACE FUNCTION execute_safe_query(query_text text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    result json;
    query_upper text;
BEGIN
    -- Convert to uppercase for checking
    query_upper := UPPER(query_text);
    
    -- Security checks: Only allow SELECT queries
    IF NOT (query_upper LIKE 'SELECT%') THEN
        RAISE EXCEPTION 'Only SELECT queries are allowed';
    END IF;
    
    -- Check for dangerous patterns
    IF query_upper ~ '(DROP|DELETE|UPDATE|INSERT|ALTER|CREATE|TRUNCATE|EXEC|EXECUTE)' THEN
        RAISE EXCEPTION 'Query contains forbidden operations';
    END IF;
    
    -- Check for SQL injection patterns
    IF query_text ~ '(--|/\*|\*/|xp_|sp_)' THEN
        RAISE EXCEPTION 'Query contains potential SQL injection patterns';
    END IF;
    
    -- Log the query for auditing (optional)
    INSERT INTO audit_logs (action, details, created_at)
    VALUES ('SAFE_QUERY_EXECUTION', jsonb_build_object('query', query_text), NOW());
    
    -- Execute the query and return results as JSON
    EXECUTE 'SELECT json_agg(row_to_json(t)) FROM (' || query_text || ') t' INTO result;
    
    -- Return empty array if no results
    IF result IS NULL THEN
        RETURN '[]'::json;
    END IF;
    
    RETURN result;
    
EXCEPTION
    WHEN OTHERS THEN
        -- Log the error
        INSERT INTO audit_logs (action, details, created_at)
        VALUES ('SAFE_QUERY_ERROR', jsonb_build_object(
            'query', query_text,
            'error', SQLERRM
        ), NOW());
        
        -- Re-raise the error
        RAISE;
END;
$$;

-- Grant execute permission to authenticated users only
GRANT EXECUTE ON FUNCTION execute_safe_query(text) TO authenticated;

-- Add comment
COMMENT ON FUNCTION execute_safe_query(text) IS 'Safely executes SELECT queries generated by the OSS LLM natural language processing service';